name: Build Go Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' 

      - name: Build the application
        run: go build -v -o peddi-tooling.exe ./main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: peddi-tooling-windows-exe
          path: peddi-tooling.exe