name: Build Go Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' 

      - name: Build the application
        run: go build -v -ldflags="-s -w" -o peddi-tooling.exe ./main.go

      - name: Build installer
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          choco install innosetup -y
          ISCC.exe installer/peddi-tooling.iss

      - name: Upload artifacts
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: peddi-tooling-artifacts
          path: |
            peddi-tooling.exe
            installer/output/peddi-tooling-installer.exe
